[project]
site_name = "Logseq (Markdown) Analyzer"
site_description = "Documentation for Logseq (Markdown) Analyzer."
site_author = "Wonyoung Jang"
site_url = "https://wonyoung-jang.github.io/logseq-analyzer"
copyright = "Copyright &copy; 2026 Wonyoung Jang"
docs_dir = "docs"
site_dir = "site"
repo_url = "https://github.com/wonyoung-jang/logseq-analyzer"
repo_name = "wonyoung-jang/logseq-analyzer"
# nav = [
#   { "Get started" = "index.md" },
#   { "Markdown in 5min" = "markdown.md" },
# ]
#extra_css = ["stylesheets/extra.css"]
#extra_javascript = ["javascripts/extra.js"]

# ----------------------------------------------------------------------------
# Section for configuring theme options
# ----------------------------------------------------------------------------
[project.theme]
font = false
#variant = "classic"
#custom_dir = "overrides"
#logo = "images/logo.png"
#favicon = "images/favicon.png"
language = "en"
features = [
    "announce.dismiss",
    #"content.action.edit",
    #"content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    # "header.autohide",
    "navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    #"navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow",
    #"toc.integrate",
]

# ----------------------------------------------------------------------------
# Project Theme Palette
# ----------------------------------------------------------------------------
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

# ----------------------------------------------------------------------------
# Project Theme Font
# ----------------------------------------------------------------------------
#[project.theme.font]
#text = "Inter"
#code = "Jetbrains Mono"

# ----------------------------------------------------------------------------
# Project Theme Icon
# ----------------------------------------------------------------------------
#[project.theme.icon]
#logo = "lucide/smile"
#repo = "lucide/smile"

# ----------------------------------------------------------------------------
# Project Extra Social
# ----------------------------------------------------------------------------
[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/wonyoung-jang/logseq-analyzer"
name = "logseq-analyzer on GitHub"

[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://linkedin.com/in/wonyoung--jang"
name = "Wonyoung Jang on LinkedIn"

# ----------------------------------------------------------------------------
# Project Plugins Mkdocstrings Handlers Python
# ----------------------------------------------------------------------------
[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["fspachinko"]

[project.plugins.mkdocstrings.handlers.python.options]
# General
show_source = false
# Headings
# Members
inherited_members = true
members_order = "source"
summary = true
# Docstrings
docstring_style = "google"
merge_init_into_class = true
# Signatures
line_length = 88
modernize_annotations = true
show_signature_annotations = true
show_signature_type_parameters= true